export enum AllCodes{
    BRANCH_TYPE = "BRANCH_TYPE",
    FORM = "FORM",
    ASS_TYPE = "AssType",
    PAYMENT_STATUS = "PAYMENT_STATUS",
    LOGIN_METHOD = "LOGIN_METHOD"
}

export enum ReaAllCode {
    REA_OWNER_TYPE = "REA_OWNER_TYPE",
    CONTRACT_ITEM_TYPE = "CONTRACT_ITEM_TYPE",
    RENTAL_PRICE_TYPE = "RENTAL_PRICE_TYPE",
    CONTRACT_STATUS = "CONTRACT_STATUS"
}
