export enum AllCodes{
    BRANCH_TYPE = "BRANCH_TYPE",
    FORM = "FORM",
    ASS_TYPE = "AssType",
    PAYMENT_STATUS = "PAYMENT_STATUS",
    LOGIN_METHOD = "LOGIN_METHOD"
}

export enum ReaAllCode {
    REA_OWNER_TYPE = "REA_OWNER_TYPE",
    CONTRACT_ITEM_TYPE = "CONTRACT_ITEM_TYPE",
    RENTAL_PRICE_TYPE = "RENTAL_PRICE_TYPE",
    CONTRACT_STATUS = "CONTRACT_STATUS",
    PROJECT_TYPE = "PROJECT_TYPE",
    PROJECT_COMPLETE_STATUS = "PROJECT_COMPLETE_STATUS",
    ENTITY_TYPE = "ENTITY_TYPE",
    LEGAL_STATUS_PROJECT_STATUS = "LEGAL_STATUS_PROJECT_STATUS",
    OWNER_TYPE = "OWNER_TYPE",
    INVEST_PROP_STATUS = "INVEST_PROP_STATUS",
    INVEST_PROP_LEGAL_STATUS = "INVEST_PROP_LEGAL_STATUS",
    INVEST_PROP_GCN_STATUS = "INVEST_PROP_GCN_STATUS",
    SODO_TRANSFER_STATUS = "SODO_TRANSFER_STATUS",
    SODO_TYPE = "SODO_TYPE",
    SODO_USE_TYPE = "SODO_USE_TYPE",
    SODO_PHYSIC_STATUS = "SODO_PHYSIC_STATUS",
    SODO_USE_STATUS = "SODO_USE_STATUS",
    SHAREHOLDER_TYPE = "SHAREHOLDER_TYPE",
}
